### ISSUE TITLE
Call to undefined function OptimistDigital\NovaBlog\Models\nova_lang_get_all_locales()

### ISSUE THREAD

**Issue by adrian-ub** [optimistdigital/nova-blog#16]
When I try to create a new Post I get the following error
` Call to undefined function OptimistDigital\NovaBlog\Models\nova_lang_get_all_locales() `

**Comment by asivaneswaran** [comment]
Having the same issue!

**Comment by adrian-ub** [comment]
You need to install another package

[https://github.com/optimistdigital/nova-lang](https://github.com/optimistdigital/nova-lang)

**Comment by KasparRosin** [comment]
Hey! Thanks for reporting this. I've released 9.2.0 of nova-blog which includes a fix. Sorry for the delay.
