### ISSUE TITLE
Change storage config

### ISSUE THREAD

**Issue by FlorentJonville** [optimistdigital/nova-blog#6]
Hello,
How can I easily change the storage path for image ?
Thanks

**Comment by KasparRosin** [comment]
@FlorentJonville You can change storage path in `config/filesystem.php` 
```php
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'), //<-- change this to your preference
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```
If that is not what you meant, please explain your use case further.
Closing this issue until then.
