### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by Dontorpedo** [optimistdigital/nova-blog#7]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for optimistdigital/nova-blog ^5.4 -> satisfiable by optimistdigital/nova-blog[5.4.0].
    - Conclusion: remove optimistdigital/nova-locale-field 2.0.0
    - Conclusion: don't install optimistdigital/nova-locale-field 2.0.0
    - optimistdigital/nova-blog 5.4.0 requires optimistdigital/nova-locale-field ^1.1.1 -> satisfiable by optimistdigital/nova-locale-field[1.1.1, 1.1.2, 1.1.3, 1.1.4].
    - Can only install one of: optimistdigital/nova-locale-field[1.1.1, 2.0.0].
    - Can only install one of: optimistdigital/nova-locale-field[1.1.2, 2.0.0].
    - Can only install one of: optimistdigital/nova-locale-field[1.1.3, 2.0.0].
    - Can only install one of: optimistdigital/nova-locale-field[1.1.4, 2.0.0].
    - Installation request for optimistdigital/nova-locale-field (locked at 2.0.0) -> satisfiable by optimistdigital/nova-locale-field[2.0.0].

pls help

**Comment by KasparRosin** [comment]
Thank you for reporting. Sorry for the late response.
Issue should be fixed in 5.5.0!
