### ISSUE TITLE
slug not well formed, it lacks dashes so cannot save by default

### ISSUE THREAD

**Issue by matovu-ronald** [optimistdigital/nova-blog#9]
Title: This is my blog title
Expected: this-is-my-blog-title
Actual Result: this is my blog title

This makes the post not save by default.

**Comment by KasparRosin** [comment]
@matovu-ronald Thanks for the issue. It seems i had removed that feature accidentally. I'll check it out.

**Comment by KasparRosin** [comment]
@matovu-ronald Thank you for reporting this. This is now fixed in [6.0.1](https://github.com/optimistdigital/nova-blog/releases/tag/6.0.1)
